### ISSUE TITLE
 Unable to send data:error

### ISSUE THREAD

**Issue by Mallon94** [UniCT-ARSLab/LWN-Simulator#1]
Anytime I try to create new device I receive this error.

**Comment by eldiablo-data** [comment]
I have the same issue. The simulator's status is always red. If I click the play button, it changes to yellow for a couple of seconds and goes back to red. Cannot add device or gateways. The console doesn't show any information.

**Comment by pippok96** [comment]
Hi everyone, the description of issue is too generic. Can you attach a screenshot with the text of error? When does it occur, exactly?

**Comment by fedyfausto** [comment]
Remember that, this simulator works with a real LoRaWAN environment (Chirpstack, TTN, etC) then you must create the devices firstly in that environment and add them in the simulator

**Comment by eldiablo-data** [comment]
Hey everyone,

I am running everything on Windows 10. The chirpstack suit is running on docker. I created a gateway in chripstack and did the same in the simulator. When I click save, it shows an error message as shown in the screenshot. The Simulator's gateway bridge in configured to 0.0.0.0:1700.
Here are some screenshots.

When creating a gateway:

![image](https://user-images.githubusercontent.com/77054827/125051170-fa15f980-e0a2-11eb-9145-1908d7e8952e.png)

![image](https://user-images.githubusercontent.com/77054827/125049949-ce464400-e0a1-11eb-9807-bc9cbbc5b7a0.png)

Chirpstack gateway:

![image](https://user-images.githubusercontent.com/77054827/125050126-f7ff6b00-e0a1-11eb-9e9b-9bb498b4f3c7.png)

While creating another gateway(The error message was different):

![image](https://user-images.githubusercontent.com/77054827/125051678-7ad4f580-e0a3-11eb-8239-5de59e4b69fe.png)

There were no error messages or warnings show in powershell, while all of these happened:

![image](https://user-images.githubusercontent.com/77054827/125051932-bc65a080-e0a3-11eb-9152-e6f06f6b965a.png)

Let me know, if you need something else.
Thanks.

**Comment by pippok96** [comment]
I fixed the bug. Moreover, I updated the repository and published a new release :)

**Comment by eldiablo-data** [comment]
I am able to create devices and run the simulator. Thanks for the fix.

**Comment by fedyfausto** [comment]
> Hey everyone,
> 
> I am running everything on Windows 10. The chirpstack suit is running on docker. I created a gateway in chripstack and did the same in the simulator. When I click save, it shows an error message as shown in the screenshot. The Simulator's gateway bridge in configured to 0.0.0.0:1700.
> Here are some screenshots.
> 
> When creating a gateway:
> 
> ![image](https://user-images.githubusercontent.com/77054827/125051170-fa15f980-e0a2-11eb-9145-1908d7e8952e.png)
> 
> ![image](https://user-images.githubusercontent.com/77054827/125049949-ce464400-e0a1-11eb-9807-bc9cbbc5b7a0.png)
> 
> Chirpstack gateway:
> 
> ![image](https://user-images.githubusercontent.com/77054827/125050126-f7ff6b00-e0a1-11eb-9e9b-9bb498b4f3c7.png)
> 
> While creating another gateway(The error message was different):
> 
> ![image](https://user-images.githubusercontent.com/77054827/125051678-7ad4f580-e0a3-11eb-8239-5de59e4b69fe.png)
> 
> There were no error messages or warnings show in powershell, while all of these happened:
> 
> ![image](https://user-images.githubusercontent.com/77054827/125051932-bc65a080-e0a3-11eb-9152-e6f06f6b965a.png)
> 
> Let me know, if you need something else.
> Thanks.

beware of the GW Bridge address, that just be the IP or DNS of your GW Bridge! (maybe in your situation must be localhost or 127.0.0.1)

**Comment by fedyfausto** [comment]
> I fixed the bug. Moreover, I updated the repository and published a new release :)

I will close the issue!
