### ISSUE TITLE
Is it possible to capture lora payload from the nodes just before it is forwarded to the gateway ?

### ISSUE THREAD

**Issue by lord-seam** [UniCT-ARSLab/LWN-Simulator#10]

**Comment by BlackPhoenixr** [comment]
I want also to capture and analyze the payload packets being send from the sensors to the gateway

**Comment by fedyfausto** [comment]
Yes the passage from virtual nodes and to the virtual gateway/real gateways is made into the simulator, and then you can print/redirect the same UDP payload that will be sent to the gateway
