### ISSUE TITLE
Not connecting to Gateway Bridge

### ISSUE THREAD

**Issue by antoniomarcossouza** [UniCT-ARSLab/LWN-Simulator#14]
I'm trying to setup the Simulator and I'm running Chirpstack for the LoRaWAN network. But when I start the simulator, it doesn't connect to the Gateway Bridge's Port :// Can you help me?

![image](https://user-images.githubusercontent.com/72502006/232057034-3c1f93cc-1bcb-4416-9910-a60116b71078.png)

**Comment by fedyfausto** [comment]
maybe a network docker problem? Did you try to set the network of container to host?

**Comment by fedyfausto** [comment]
Closing the issue because is considered solved
