### ISSUE TITLE
Unable to view JoinRequest on LoRaWAN Frames

### ISSUE THREAD

**Issue by khushigarg12** [UniCT-ARSLab/LWN-Simulator#19]
I have set up a testing environment with ChirpStack and the LWN Simulator on a Linux (Ubuntu) virtual machine. In this environment, I created a virtual gateway using the LWN Simulator, and the simulator's logs indicate that it is sending join request frames.
WhatsApp Image 2023-09-15 at 10 26 18 AM
Problem:
The issue I'm facing is that I cannot see these join request frames in the ChirpStack UI's LoRaWAN frames section. Despite the simulator sending the join requests, there is no visibility or record of them within the ChirpStack application.
WhatsApp Image 2023-09-15 at 10 20 32 AM

My current Setup:
Installed ChirpStack (v4) according to the "Getting Started with Debian/Ubuntu" guide.
Configured and launched the LWN Simulator.
Created a virtual gateway within the LWN Simulator.
Initiated join requests from the LWN Simulator.

Environment:
ChirpStack Version: v4
Operating System: Ubuntu 22.04
ChirpStack Gateway Bridge Configuration Details:
WhatsApp Image 2023-09-14 at 4 37 53 PM
WhatsApp Image 2023-09-14 at 4 50 22 PM

This issue is a crucial step toward achieving my ultimate goal of data transfer from ChirpStack to Azure IoT Hub.

**Comment by fedyfausto** [comment]
Can not see the images, let's schedule a call if you want

**Comment by khushigarg12** [comment]
Yeah sure
![image](https://github.com/UniCT-ARSLab/LWN-Simulator/assets/145097016/f1c9af6a-b389-49bb-93b9-1499297a9643)
![image](https://github.com/UniCT-ARSLab/LWN-Simulator/assets/145097016/de74b440-f133-4b05-adab-ebfb2dbdddb4)
![image](https://github.com/UniCT-ARSLab/LWN-Simulator/assets/145097016/2b47e624-5047-44ee-8600-df20d3674005)
![image](https://github.com/UniCT-ARSLab/LWN-Simulator/assets/145097016/5a7eb7d1-b581-42e0-baf7-7f09cc7ea252)

**Comment by fedyfausto** [comment]
did you try the release version?

**Comment by fedyfausto** [comment]
Any news? 

> Yeah sure @fedyfausto ![image](https://private-user-images.githubusercontent.com/145097016/271628549-f1c9af6a-b389-49bb-93b9-1499297a9643.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDE4ODE0ODUsIm5iZiI6MTcwMTg4MTE4NSwicGF0aCI6Ii8xNDUwOTcwMTYvMjcxNjI4NTQ5LWYxYzlhZjZhLWIzODktNDliYi05M2I5LTE0OTkyOTdhOTY0My5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBSVdOSllBWDRDU1ZFSDUzQSUyRjIwMjMxMjA2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDIzMTIwNlQxNjQ2MjVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1lNGQ3ZTA3NGI1YTYxZDYyMGQxNGIwY2VjMTFhZWM2OTBhZTI5ODA2ZDViNWE3YjMyZGJkZDUyYTAzYzFiNTk5JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.6ys1oYtOF19Nf_n7YJ3hZOouZDTpzdVj057FFaFrO_4) ![image](https://private-user-images.githubusercontent.com/145097016/271628827-de74b440-f133-4b05-adab-ebfb2dbdddb4.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDE4ODE0ODUsIm5iZiI6MTcwMTg4MTE4NSwicGF0aCI6Ii8xNDUwOTcwMTYvMjcxNjI4ODI3LWRlNzRiNDQwLWYxMzMtNGIwNS1hZGFiLWViZmIyZGJkZGRiNC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBSVdOSllBWDRDU1ZFSDUzQSUyRjIwMjMxMjA2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDIzMTIwNlQxNjQ2MjVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT03OGNjMzZjMTFlMzU1MzZmZGIyMzFlOGY0MWFmZjZjYTYzM2ZkYzc1OTJiZTEwMTRlNWEzNzdhOTE1NDBjYTcwJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.CF4HWPZZseDfTRgCptNIfKq-Q9Wva6GmmeSlT_oSemw) ![image](https://private-user-images.githubusercontent.com/145097016/271629149-2b47e624-5047-44ee-8600-df20d3674005.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDE4ODE0ODUsIm5iZiI6MTcwMTg4MTE4NSwicGF0aCI6Ii8xNDUwOTcwMTYvMjcxNjI5MTQ5LTJiNDdlNjI0LTUwNDctNDRlZS04NjAwLWRmMjBkMzY3NDAwNS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBSVdOSllBWDRDU1ZFSDUzQSUyRjIwMjMxMjA2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDIzMTIwNlQxNjQ2MjVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0wMzAxODdkZDBkYjA3Y2I3MmRiMzdjYTgwOWIzZDQzZDRkYjNlYmFjZjY0ODAzYjA5MDUzYmE4ZmQzZWZjOGE0JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.wenqKYNFLrNtficvAhAmyE0RQymkTOcjL-7mM4_9nXw) ![image](https://private-user-images.githubusercontent.com/145097016/271629276-5a7eb7d1-b581-42e0-baf7-7f09cc7ea252.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDE4ODE0ODUsIm5iZiI6MTcwMTg4MTE4NSwicGF0aCI6Ii8xNDUwOTcwMTYvMjcxNjI5Mjc2LTVhN2ViN2QxLWI1ODEtNDJlMC1iYWY3LTdmMDljYzdlYTI1Mi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBSVdOSllBWDRDU1ZFSDUzQSUyRjIwMjMxMjA2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDIzMTIwNlQxNjQ2MjVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0zNTc1YTcxYTE2YWI2OWM5MjAzN2ZjMzEwY2VmZjNiOTgyZmRjOTE1MWYxMDk4YTNmMTc5ZmM3NzhjZGY0ZDQxJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.ze8vJg7hAQAjxJPGdNNwdo-ycZGHRKhvynABp1dmjuc)
