### ISSUE TITLE
Device are not seen on chirpstack

### ISSUE THREAD

**Issue by piyushkanadje** [UniCT-ARSLab/LWN-Simulator#25]
My device is not seen on the chirpstack dashboard. I am using region eu868.

**Comment by fedyfausto** [comment]
Hello! We are working on a new 1.0.3 version that will be released soon. Meanwhile, you can download the 1.0.2 version from the release section
https://github.com/UniCT-ARSLab/LWN-Simulator/releases/tag/v1.0.2
