### ISSUE TITLE
Problem on downlink

### ISSUE THREAD

**Issue by bouhenic** [UniCT-ARSLab/LWN-Simulator#26]
Hi,
There is a problem on downlink message.
For OTAA, no downlink accept. 
For ABP, of course we can register the device. Uplink works well. But the downlink message doesn't works.

**Comment by fedyfausto** [comment]
Hello! We are working on a new 1.0.3 version that will be released soon. Meanwhile, you can download the 1.0.2 version from the release section
https://github.com/UniCT-ARSLab/LWN-Simulator/releases/tag/v1.0.2
