### ISSUE TITLE
Statik is an unmentioned requirement

### ISSUE THREAD

**Issue by thayol** [UniCT-ARSLab/LWN-Simulator#29]
While running `$ make build` I encountered the following problem:

```log
Building the LWN Simulator
Building the User Interface
/bin/sh: line 1: statik: command not found
make: *** [Makefile:8: build] Error 127
```

It's interesting because I ran `$ make install-dep` and I've even tried to just run `go install github.com/rakyll/statik` by itself but it did not give me a globally available command.

I've resolved the problem on two systems via two different solutions:
* Fedora 39: `sudo dnf install golang-github-rakyll-statik`
* Debian 11: `sudo apt update && sudo apt install golang-statik`

I think the most sensible solution would be to list the tool as a requirement (or export the one installed by `make install-dep` to `PATH`)

**Comment by LightDestory** [comment]
The install-dep task on the makefile will install statik as a go binary module. 

The correct way is to add in your system PATH the [GOPATH](https://go.dev/wiki/GOPATH). I do not think the makefile should alter the user's system PATH.

I am going to add a note in the README regarding this issue.
