### ISSUE TITLE
Parameters to be set in the config.json file

### ISSUE THREAD

**Issue by Sudip-star-a11y** [UniCT-ARSLab/LWN-Simulator#3]
Hello,

I am having Ubuntu 18.04 running as VM on windows host. In the same VM I have installed all the Chirpstack components namely Gateway-Bridge, network Server and Application server. I have installed the LWN-Simulator too in the same VM but while executing the 'make run' command I am getting the error as :

**_**2sudip@sudip_ubuntu:~/LWN-Simulator$ make run
2021/11/09 14:37:10 LWN Simulator is online...
2021/11/09 14:37:10 [WS]: Listen [ 192.168.1.5:8000 ]
2021/11/09 14:37:10 [WS] [ERROR]: listen tcp 192.168.1.5:8000: bind: address already in use**_**

192.168.1.5- is my VM ip address.

The same 8000 port I have used while adding network server in the application server web interface.
'localhost:8000'.

What shall I do to get the websocket of the simulator to get connected?  

Please help!!

**Comment by fedyfausto** [comment]
This error means that the port is used by another process, but you can change the port for the LWN Simulator in the config file.
