### ISSUE TITLE
Use a binary payload

### ISSUE THREAD

**Issue by fixmaker** [UniCT-ARSLab/LWN-Simulator#4]
Is it possible to set up a virtual device with a binary payload?

I would like to simulate a LoRaWAN payload of bytes that cannot be represented by a simple ASCII string, but there does not seem to be a way to configure that in the UI.

**Comment by fedyfausto** [comment]
It will be implemented in the next update!

**Comment by fedyfausto** [comment]
Closing the issue for future update
