### ISSUE TITLE
How to connect virtual gateway to ChirpStack open-source LoRaWAN® Network Server?

### ISSUE THREAD

**Issue by sergorl** [UniCT-ARSLab/LWN-Simulator#5]
I created Gateway Bridge's address: `127.0.0.1:8081`  and virtual gateway with MAC `29272682558d9843`.

So how to connect virtual gateway to [ChirpStack open-source LoRaWAN® Network Server](https://www.chirpstack.io/project/)?

**Comment by fedyfausto** [comment]
Hello, sergol! You must add it with that MAC address in the chirpstack dashboard such as a normal Gateway

**Comment by sergorl** [comment]
@fedyfausto , what'are the values for `Gateway's IPv4` and `Gateway's Port`?

**Comment by fedyfausto** [comment]
The IP of your Gateway and the UDP port of Semtech UDP

**Comment by fedyfausto** [comment]
Closing the issue, I think the problem was solved
