### ISSUE TITLE
How to connect Chirpstack device and generate testing data from simulator device?

### ISSUE THREAD

**Issue by zhgchen** [UniCT-ARSLab/LWN-Simulator#6]
I have copied DevEUI to Chirpstack's device. The gateway can be associated correctly. But "Last seen at" is always "never" for device.

**Comment by fedyfausto** [comment]
Do the Gateway and devices work?

**Comment by zhgchen** [comment]
Gateway seems work and is visible at "Active gateways", but device is not available at "Active devices"

From LWN-Simulator console:
2022/04/20 10:31:26 DEV[LWN-Dev-1] |Activation| {A}: None downlink received
2022/04/20 10:31:26 DEV[LWN-Dev-1] |Activation| {A}: Unjoined
2022/04/20 10:31:26 DEV[LWN-Dev-1] |Activation| {A}: JOIN REQUEST sent
2022/04/20 10:31:26 DEV[LWN-Dev-1] |Activation| {A}: Open RXs
2022/04/20 10:31:26 GW[LWN-GT-1]: PUSH DATA send
2022/04/20 10:31:27 GW[LWN-GT-1]: PUSH ACK received
2022/04/20 10:31:28 GW[LWN-GT-1]: PULL RESP received
2022/04/20 10:31:28 GW[LWN-GT-1]: TX ACK sent

From NS console (dev_eui is the one configured from LWN-Simulator ):
time="2022-04-20T10:01:01.1066545+08:00" level=info msg="backend/joinserver: sending response" dev_eui=218bfeacd34a8728 message_type=JoinAns receiver_id=000000 result_code=Success sender_id=0000000000000000 transaction_id=4181779636
 
From Application console (gateway_id and dev_eui are set from LWN-Simulator ):
time="2022-04-20T10:26:02.5749609+08:00" level=error msg="log uplink frame for device error" ctx_id="<nil>" error="redis xadd error: EXECABORT Transaction discarded because of previous errors."
time="2022-04-20T10:26:02.5863415+08:00" level=info msg="lorawan/backend: finished backend api call" message_type=JoinReq protocol_version=1.0 receiver_id=0000000000000000 result_code=Success sender_id=000000 transaction_id=3712802559
time="2022-04-20T10:26:02.5868529+08:00" level=info msg="sent uplink meta-data to network-controller" ctx_id=17bf367e-0d56-4f94-bb80-924cb3789fdb dev_eui=218bfeacd34a8728
time="2022-04-20T10:26:02.5873701+08:00" level=info msg="device-queue flushed" ctx_id=17bf367e-0d56-4f94-bb80-924cb3789fdb dev_eui=218bfeacd34a8728
time="2022-04-20T10:26:02.6147353+08:00" level=info msg="device-session saved" ctx_id=17bf367e-0d56-4f94-bb80-924cb3789fdb dev_addr=002ee668 dev_eui=218bfeacd34a8728
time="2022-04-20T10:26:02.6172662+08:00" level=info msg="device-activation created" ctx_id=17bf367e-0d56-4f94-bb80-924cb3789fdb dev_eui=218bfeacd34a8728 id=897
time="2022-04-20T10:26:02.6355111+08:00" level=info msg="device updated" ctx_id=17bf367e-0d56-4f94-bb80-924cb3789fdb dev_eui=218bfeacd34a8728
time="2022-04-20T10:26:02.6546841+08:00" level=info msg="gateway/mqtt: publishing gateway command" command=down downlink_id=17bf367e-0d56-4f94-bb80-924cb3789fdb gateway_id=9710a2550134250f qos=0 topic=gateway/9710a2550134250f/command/down
time="2022-04-20T10:26:02.6631232+08:00" level=info msg="storage: downlink-frame saved" ctx_id=17bf367e-0d56-4f94-bb80-924cb3789fdb token=39229
time="2022-04-20T10:26:04.3428469+08:00" level=info msg="backend/gateway: downlink tx acknowledgement received" downlink_id=17bf367e-0d56-4f94-bb80-924cb3789fdb gateway_id=9710a2550134250f
time="2022-04-20T10:26:04.3435334+08:00" level=info msg="sent downlink meta-data to network-controller" ctx_id=17bf367e-0d56-4f94-bb80-924cb3789fdb
time="2022-04-20T10:26:04.3435334+08:00" level=error msg="log downlink frame for gateway error" ctx_id=17bf367e-0d56-4f94-bb80-924cb3789fdb error="redis xadd error: EXECABORT Transaction discarded because of previous errors."
time="2022-04-20T10:26:04.379772+08:00" level=error msg="log downlink frame for device error" ctx_id=17bf367e-0d56-4f94-bb80-924cb3789fdb error="redis xadd error: EXECABORT Transaction discarded because of previous errors."

**Comment by Kampftoast** [comment]
Might be a little late but here's how I got it working:
1. Configure device in Simulator
2. Create a device in Chirpstack
3. Then use Chripstack API Endpoint to first get a JWD-Token via [POST] [/api/internal/login]  and then use route [GET][/api/devices/{dev_eui}/activation] to activate your device manually.

**Comment by BlackPhoenixr** [comment]
@Kampftoast I cannot find the /api/internal/login on Swagger UI. Am i missing a way of accessing Chripstack API Endpoint?

**Comment by fedyfausto** [comment]
The frequency must be the same on the Chirpstack and in the Simulator. The device auth is ABP?

**Comment by fedyfausto** [comment]
Closing the issue, I think the problem was solved
